/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminEntry {
  'principal' : Principal,
  'assignedAt' : Timestamp,
  'role' : AdminRole,
}
export type AdminRole = { 'manager' : null } |
  { 'owner' : null } |
  { 'support' : null } |
  { 'viewer' : null };
export interface AnalyticsSettings {
  'tiktokPixelId' : string,
  'metaPixelId' : string,
  'ga4Id' : string,
}
export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'performer' : Principal,
  'target' : [] | [string],
  'timestamp' : Timestamp,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedDate' : bigint,
  'featuredImage' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'slug' : string,
  'author' : string,
  'updatedAt' : bigint,
  'excerpt' : string,
}
export interface Booking {
  'id' : BookingId,
  'damageNotes' : string,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'cryptoTxRef' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'endDate' : Timestamp,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'damageClaimFlag' : boolean,
  'totalCost' : bigint,
  'stripeSessionId' : [] | [string],
  'vehicleId' : VehicleId,
  'startDate' : Timestamp,
}
export type BookingId = bigint;
export type BookingStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'returned' : null };
export interface CeoProfile {
  'title' : string,
  'name' : string,
  'instagramHandle' : string,
  'description' : string,
  'photoUrl' : string,
}
export interface ComparisonRow {
  'feature' : string,
  'annual' : boolean,
  'monthly' : boolean,
}
export interface EmailSubscriber { 'subscribedAt' : bigint, 'email' : string }
export interface ErrorLogEntry {
  'id' : bigint,
  'errorType' : string,
  'message' : string,
  'timestamp' : bigint,
  'principalId' : [] | [string],
}
export interface IDVerification {
  'status' : IDVerificationStatus,
  'bookingId' : string,
  'userId' : Principal,
  'ssnLast4' : string,
  'submittedAt' : bigint,
  'reviewedAt' : bigint,
  'licensePhotoId' : string,
  'adminNotes' : string,
}
export type IDVerificationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type MembershipPlan = { 'annual' : null } |
  { 'monthly' : null };
export interface MembershipPlanConfig {
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'price' : number,
}
export type MembershipStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'failed' : null };
export interface Message {
  'id' : MessageId,
  'content' : string,
  'bookingId' : bigint,
  'timestamp' : bigint,
  'senderRole' : string,
  'senderId' : UserId,
}
export type MessageId = bigint;
export type PaymentMethod = { 'creditCard' : null } |
  { 'applePay' : null } |
  { 'crypto' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface PlanConfigs {
  'annual' : MembershipPlanConfig,
  'monthly' : MembershipPlanConfig,
}
export interface Review {
  'id' : ReviewId,
  'bookingId' : bigint,
  'reviewerId' : UserId,
  'comment' : string,
  'timestamp' : bigint,
  'rating' : bigint,
  'vehicleId' : bigint,
}
export type ReviewId = bigint;
export type Timestamp = bigint;
export interface TripPhoto {
  'id' : bigint,
  'bookingId' : string,
  'phase' : TripPhotoPhase,
  'uploadedAt' : bigint,
  'uploaderId' : Principal,
  'photoId' : string,
}
export type TripPhotoPhase = { 'after' : null } |
  { 'before' : null };
export type UserId = Principal;
export interface UserMembership {
  'status' : MembershipStatus,
  'endDate' : Timestamp,
  'userId' : UserId,
  'plan' : MembershipPlan,
  'startDate' : Timestamp,
}
export interface UserProfile {
  'principal' : UserId,
  'displayName' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'membershipStatus' : [] | [MembershipStatus],
}
export interface Vehicle {
  'id' : VehicleId,
  'mileageLimit' : bigint,
  'dailyRate' : bigint,
  'sortOrder' : bigint,
  'name' : string,
  'color' : string,
  'year' : bigint,
  'bookedRanges' : Array<[bigint, bigint]>,
  'description' : string,
  'deposit' : bigint,
  'available' : boolean,
  'imageUrl' : string,
  'rules' : Array<string>,
}
export type VehicleId = bigint;
export interface VehicleInput {
  'mileageLimit' : bigint,
  'dailyRate' : bigint,
  'name' : string,
  'color' : string,
  'year' : bigint,
  'description' : string,
  'deposit' : bigint,
  'available' : boolean,
  'imageUrl' : string,
  'rules' : Array<string>,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAdmin' : ActorMethod<[Principal], { 'ok' : null } | { 'err' : string }>,
  'addFavorite' : ActorMethod<[string], undefined>,
  'addTripPhoto' : ActorMethod<
    [string, string, string],
    { 'ok' : TripPhoto } |
      { 'err' : string }
  >,
  'adminAddVehicle' : ActorMethod<
    [VehicleInput],
    { 'ok' : Vehicle } |
      { 'err' : string }
  >,
  'adminCreateBlogPost' : ActorMethod<
    [string, string, string, string, string, string, bigint, boolean],
    { 'ok' : BlogPost } |
      { 'err' : string }
  >,
  'adminDeleteBlogPost' : ActorMethod<[bigint], boolean>,
  'adminDeleteVehicle' : ActorMethod<
    [VehicleId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetAllBookings' : ActorMethod<[], Array<Booking>>,
  'adminGetEmailSubscribers' : ActorMethod<[], Array<EmailSubscriber>>,
  'adminGetPendingVerifications' : ActorMethod<[], Array<IDVerification>>,
  'adminListAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'adminListUsers' : ActorMethod<[], Array<UserProfile>>,
  'adminReportDamage' : ActorMethod<
    [BookingId, string],
    { 'ok' : Booking } |
      { 'err' : string }
  >,
  'adminReviewVerification' : ActorMethod<
    [string, boolean, string],
    { 'ok' : IDVerification } |
      { 'err' : string }
  >,
  'adminSendPromoEmail' : ActorMethod<
    [string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'adminSetAnalyticsSettings' : ActorMethod<
    [AnalyticsSettings],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetMembershipPricing' : ActorMethod<
    [number, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetOpenAIKey' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetSiteStats' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetVehiclePhoto' : ActorMethod<
    [VehicleId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetVehicleSortOrders' : ActorMethod<
    [Array<[VehicleId, bigint]>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateBlogPost' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [boolean],
    ],
    { 'ok' : BlogPost } |
      { 'err' : string }
  >,
  'adminUpdateBookingStatus' : ActorMethod<
    [BookingId, BookingStatus],
    { 'ok' : Booking } |
      { 'err' : string }
  >,
  'adminUpdatePolicy' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateVehicle' : ActorMethod<
    [VehicleId, VehicleInput],
    { 'ok' : Vehicle } |
      { 'err' : string }
  >,
  'askChat' : ActorMethod<[string, string], string>,
  'assignRole' : ActorMethod<
    [Principal, AdminRole],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'cancelBooking' : ActorMethod<[BookingId], boolean>,
  'cancelMembership' : ActorMethod<[], boolean>,
  'checkVehicleAvailability' : ActorMethod<
    [VehicleId, bigint, bigint],
    boolean
  >,
  'clearErrorLogs' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'createBooking' : ActorMethod<
    [bigint, bigint, bigint, PaymentMethod],
    { 'ok' : Booking } |
      { 'err' : string }
  >,
  'getAdminRole' : ActorMethod<[Principal], [] | [AdminRole]>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'activeUserCount' : bigint,
      'bookingCountByVehicle' : Array<[string, bigint]>,
      'fleetUtilizationPercent' : number,
      'totalRevenue' : number,
    }
  >,
  'getAnalyticsSettings' : ActorMethod<[], AnalyticsSettings>,
  'getAuditLog' : ActorMethod<
    [],
    { 'ok' : Array<AuditLog> } |
      { 'err' : string }
  >,
  'getAverageRating' : ActorMethod<[bigint], bigint>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getBookingById' : ActorMethod<[BookingId], [] | [Booking]>,
  'getCeoProfile' : ActorMethod<[], CeoProfile>,
  'getComparisonRows' : ActorMethod<[], Array<ComparisonRow>>,
  'getErrorLogs' : ActorMethod<
    [],
    { 'ok' : Array<ErrorLogEntry> } |
      { 'err' : string }
  >,
  'getMembershipPricing' : ActorMethod<
    [],
    { 'annual' : number, 'monthly' : number }
  >,
  'getMessages' : ActorMethod<
    [bigint],
    { 'ok' : Array<Message> } |
      { 'err' : string }
  >,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyFavorites' : ActorMethod<[], Array<string>>,
  'getMyMembership' : ActorMethod<[], [] | [UserMembership]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyReferralCode' : ActorMethod<[], string>,
  'getPlanConfigs' : ActorMethod<[], PlanConfigs>,
  'getPolicies' : ActorMethod<
    [],
    {
      'insuranceWaiverTerms' : string,
      'cancellationPolicy' : string,
      'damagePolicy' : string,
    }
  >,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getReferralStats' : ActorMethod<
    [],
    { 'code' : string, 'referralCount' : bigint }
  >,
  'getSiteStats' : ActorMethod<
    [],
    {
      'conciergeSupport' : string,
      'eliteVehicles' : bigint,
      'fiveStarReviews' : string,
      'satisfiedClients' : string,
    }
  >,
  'getTripPhotos' : ActorMethod<[string], Array<TripPhoto>>,
  'getVehicle' : ActorMethod<[VehicleId], [] | [Vehicle]>,
  'getVehicleReviews' : ActorMethod<[bigint], Array<Review>>,
  'getVehicleSortOrders' : ActorMethod<[], Array<[VehicleId, bigint]>>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'listAdminsWithRoles' : ActorMethod<[], Array<AdminEntry>>,
  'listPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listVehicles' : ActorMethod<[], Array<Vehicle>>,
  'registerProfile' : ActorMethod<[string, string], UserProfile>,
  'removeAdmin' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeFavorite' : ActorMethod<[string], undefined>,
  'sendMessage' : ActorMethod<
    [bigint, string],
    { 'ok' : Message } |
      { 'err' : string }
  >,
  'setCeoProfile' : ActorMethod<[CeoProfile], undefined>,
  'setComparisonRows' : ActorMethod<
    [Array<ComparisonRow>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setPlanConfigs' : ActorMethod<
    [PlanConfigs],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitIDVerification' : ActorMethod<
    [string, string, string],
    { 'ok' : IDVerification } |
      { 'err' : string }
  >,
  'submitReview' : ActorMethod<
    [bigint, bigint, bigint, string],
    { 'ok' : Review } |
      { 'err' : string }
  >,
  'subscribeMembership' : ActorMethod<
    [MembershipPlan],
    { 'ok' : UserMembership } |
      { 'err' : string }
  >,
  'subscribeToEmailList' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transferOwnership' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateMembershipStatus' : ActorMethod<
    [UserId, MembershipStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProfile' : ActorMethod<[string, string], [] | [UserProfile]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];