/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TripPhotoPhase = IDL.Variant({
  'after' : IDL.Null,
  'before' : IDL.Null,
});
export const TripPhoto = IDL.Record({
  'id' : IDL.Nat,
  'bookingId' : IDL.Text,
  'phase' : TripPhotoPhase,
  'uploadedAt' : IDL.Int,
  'uploaderId' : IDL.Principal,
  'photoId' : IDL.Text,
});
export const VehicleInput = IDL.Record({
  'mileageLimit' : IDL.Nat,
  'dailyRate' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'deposit' : IDL.Nat,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'rules' : IDL.Vec(IDL.Text),
});
export const VehicleId = IDL.Nat;
export const Vehicle = IDL.Record({
  'id' : VehicleId,
  'mileageLimit' : IDL.Nat,
  'dailyRate' : IDL.Nat,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'bookedRanges' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int)),
  'description' : IDL.Text,
  'deposit' : IDL.Nat,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'rules' : IDL.Vec(IDL.Text),
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedDate' : IDL.Int,
  'featuredImage' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'updatedAt' : IDL.Int,
  'excerpt' : IDL.Text,
});
export const BookingId = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'returned' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'creditCard' : IDL.Null,
  'applePay' : IDL.Null,
  'crypto' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Booking = IDL.Record({
  'id' : BookingId,
  'damageNotes' : IDL.Text,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'cryptoTxRef' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'endDate' : Timestamp,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'damageClaimFlag' : IDL.Bool,
  'totalCost' : IDL.Nat,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'vehicleId' : VehicleId,
  'startDate' : Timestamp,
});
export const EmailSubscriber = IDL.Record({
  'subscribedAt' : IDL.Int,
  'email' : IDL.Text,
});
export const IDVerificationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const IDVerification = IDL.Record({
  'status' : IDVerificationStatus,
  'bookingId' : IDL.Text,
  'userId' : IDL.Principal,
  'ssnLast4' : IDL.Text,
  'submittedAt' : IDL.Int,
  'reviewedAt' : IDL.Int,
  'licensePhotoId' : IDL.Text,
  'adminNotes' : IDL.Text,
});
export const MembershipStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'failed' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'membershipStatus' : IDL.Opt(MembershipStatus),
});
export const AnalyticsSettings = IDL.Record({
  'tiktokPixelId' : IDL.Text,
  'metaPixelId' : IDL.Text,
  'ga4Id' : IDL.Text,
});
export const AdminRole = IDL.Variant({
  'manager' : IDL.Null,
  'owner' : IDL.Null,
  'support' : IDL.Null,
  'viewer' : IDL.Null,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'performer' : IDL.Principal,
  'target' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
});
export const CeoProfile = IDL.Record({
  'title' : IDL.Text,
  'name' : IDL.Text,
  'instagramHandle' : IDL.Text,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const ComparisonRow = IDL.Record({
  'feature' : IDL.Text,
  'annual' : IDL.Bool,
  'monthly' : IDL.Bool,
});
export const ErrorLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'errorType' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'principalId' : IDL.Opt(IDL.Text),
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'bookingId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'senderRole' : IDL.Text,
  'senderId' : UserId,
});
export const MembershipPlan = IDL.Variant({
  'annual' : IDL.Null,
  'monthly' : IDL.Null,
});
export const UserMembership = IDL.Record({
  'status' : MembershipStatus,
  'endDate' : Timestamp,
  'userId' : UserId,
  'plan' : MembershipPlan,
  'startDate' : Timestamp,
});
export const MembershipPlanConfig = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const PlanConfigs = IDL.Record({
  'annual' : MembershipPlanConfig,
  'monthly' : MembershipPlanConfig,
});
export const ReviewId = IDL.Nat;
export const Review = IDL.Record({
  'id' : ReviewId,
  'bookingId' : IDL.Nat,
  'reviewerId' : UserId,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
  'vehicleId' : IDL.Nat,
});
export const AdminEntry = IDL.Record({
  'principal' : IDL.Principal,
  'assignedAt' : Timestamp,
  'role' : AdminRole,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addFavorite' : IDL.Func([IDL.Text], [], []),
  'addTripPhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : TripPhoto, 'err' : IDL.Text })],
      [],
    ),
  'adminAddVehicle' : IDL.Func(
      [VehicleInput],
      [IDL.Variant({ 'ok' : Vehicle, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Bool,
      ],
      [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminDeleteVehicle' : IDL.Func(
      [VehicleId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
  'adminGetEmailSubscribers' : IDL.Func([], [IDL.Vec(EmailSubscriber)], []),
  'adminGetPendingVerifications' : IDL.Func([], [IDL.Vec(IDVerification)], []),
  'adminListAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], []),
  'adminListUsers' : IDL.Func([], [IDL.Vec(UserProfile)], []),
  'adminReportDamage' : IDL.Func(
      [BookingId, IDL.Text],
      [IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text })],
      [],
    ),
  'adminReviewVerification' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text],
      [IDL.Variant({ 'ok' : IDVerification, 'err' : IDL.Text })],
      [],
    ),
  'adminSendPromoEmail' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'adminSetAnalyticsSettings' : IDL.Func(
      [AnalyticsSettings],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetMembershipPricing' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetOpenAIKey' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetSiteStats' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetVehiclePhoto' : IDL.Func(
      [VehicleId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetVehicleSortOrders' : IDL.Func(
      [IDL.Vec(IDL.Tuple(VehicleId, IDL.Nat))],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateBlogPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateBookingStatus' : IDL.Func(
      [BookingId, BookingStatus],
      [IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdatePolicy' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateVehicle' : IDL.Func(
      [VehicleId, VehicleInput],
      [IDL.Variant({ 'ok' : Vehicle, 'err' : IDL.Text })],
      [],
    ),
  'askChat' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignRole' : IDL.Func(
      [IDL.Principal, AdminRole],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'cancelBooking' : IDL.Func([BookingId], [IDL.Bool], []),
  'cancelMembership' : IDL.Func([], [IDL.Bool], []),
  'checkVehicleAvailability' : IDL.Func(
      [VehicleId, IDL.Int, IDL.Int],
      [IDL.Bool],
      ['query'],
    ),
  'clearErrorLogs' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Int, PaymentMethod],
      [IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text })],
      [],
    ),
  'getAdminRole' : IDL.Func([IDL.Principal], [IDL.Opt(AdminRole)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeUserCount' : IDL.Nat,
          'bookingCountByVehicle' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'fleetUtilizationPercent' : IDL.Float64,
          'totalRevenue' : IDL.Float64,
        }),
      ],
      [],
    ),
  'getAnalyticsSettings' : IDL.Func([], [AnalyticsSettings], ['query']),
  'getAuditLog' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(AuditLog), 'err' : IDL.Text })],
      ['query'],
    ),
  'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBookingById' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getCeoProfile' : IDL.Func([], [CeoProfile], ['query']),
  'getComparisonRows' : IDL.Func([], [IDL.Vec(ComparisonRow)], ['query']),
  'getErrorLogs' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(ErrorLogEntry), 'err' : IDL.Text })],
      [],
    ),
  'getMembershipPricing' : IDL.Func(
      [],
      [IDL.Record({ 'annual' : IDL.Float64, 'monthly' : IDL.Float64 })],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(Message), 'err' : IDL.Text })],
      [],
    ),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getMyMembership' : IDL.Func([], [IDL.Opt(UserMembership)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyReferralCode' : IDL.Func([], [IDL.Text], []),
  'getPlanConfigs' : IDL.Func([], [PlanConfigs], ['query']),
  'getPolicies' : IDL.Func(
      [],
      [
        IDL.Record({
          'insuranceWaiverTerms' : IDL.Text,
          'cancellationPolicy' : IDL.Text,
          'damagePolicy' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getReferralStats' : IDL.Func(
      [],
      [IDL.Record({ 'code' : IDL.Text, 'referralCount' : IDL.Nat })],
      [],
    ),
  'getSiteStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'conciergeSupport' : IDL.Text,
          'eliteVehicles' : IDL.Nat,
          'fiveStarReviews' : IDL.Text,
          'satisfiedClients' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getTripPhotos' : IDL.Func([IDL.Text], [IDL.Vec(TripPhoto)], []),
  'getVehicle' : IDL.Func([VehicleId], [IDL.Opt(Vehicle)], ['query']),
  'getVehicleReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getVehicleSortOrders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(VehicleId, IDL.Nat))],
      ['query'],
    ),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listAdminsWithRoles' : IDL.Func([], [IDL.Vec(AdminEntry)], ['query']),
  'listPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'registerProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'removeAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeFavorite' : IDL.Func([IDL.Text], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
      [],
    ),
  'setCeoProfile' : IDL.Func([CeoProfile], [], []),
  'setComparisonRows' : IDL.Func(
      [IDL.Vec(ComparisonRow)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setPlanConfigs' : IDL.Func(
      [PlanConfigs],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitIDVerification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDVerification, 'err' : IDL.Text })],
      [],
    ),
  'submitReview' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Review, 'err' : IDL.Text })],
      [],
    ),
  'subscribeMembership' : IDL.Func(
      [MembershipPlan],
      [IDL.Variant({ 'ok' : UserMembership, 'err' : IDL.Text })],
      [],
    ),
  'subscribeToEmailList' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transferOwnership' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateMembershipStatus' : IDL.Func(
      [UserId, MembershipStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(UserProfile)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TripPhotoPhase = IDL.Variant({
    'after' : IDL.Null,
    'before' : IDL.Null,
  });
  const TripPhoto = IDL.Record({
    'id' : IDL.Nat,
    'bookingId' : IDL.Text,
    'phase' : TripPhotoPhase,
    'uploadedAt' : IDL.Int,
    'uploaderId' : IDL.Principal,
    'photoId' : IDL.Text,
  });
  const VehicleInput = IDL.Record({
    'mileageLimit' : IDL.Nat,
    'dailyRate' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'deposit' : IDL.Nat,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'rules' : IDL.Vec(IDL.Text),
  });
  const VehicleId = IDL.Nat;
  const Vehicle = IDL.Record({
    'id' : VehicleId,
    'mileageLimit' : IDL.Nat,
    'dailyRate' : IDL.Nat,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'bookedRanges' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int)),
    'description' : IDL.Text,
    'deposit' : IDL.Nat,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'rules' : IDL.Vec(IDL.Text),
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedDate' : IDL.Int,
    'featuredImage' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'updatedAt' : IDL.Int,
    'excerpt' : IDL.Text,
  });
  const BookingId = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'returned' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'creditCard' : IDL.Null,
    'applePay' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Booking = IDL.Record({
    'id' : BookingId,
    'damageNotes' : IDL.Text,
    'status' : BookingStatus,
    'paymentStatus' : PaymentStatus,
    'cryptoTxRef' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'endDate' : Timestamp,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'damageClaimFlag' : IDL.Bool,
    'totalCost' : IDL.Nat,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'vehicleId' : VehicleId,
    'startDate' : Timestamp,
  });
  const EmailSubscriber = IDL.Record({
    'subscribedAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const IDVerificationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const IDVerification = IDL.Record({
    'status' : IDVerificationStatus,
    'bookingId' : IDL.Text,
    'userId' : IDL.Principal,
    'ssnLast4' : IDL.Text,
    'submittedAt' : IDL.Int,
    'reviewedAt' : IDL.Int,
    'licensePhotoId' : IDL.Text,
    'adminNotes' : IDL.Text,
  });
  const MembershipStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'failed' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'membershipStatus' : IDL.Opt(MembershipStatus),
  });
  const AnalyticsSettings = IDL.Record({
    'tiktokPixelId' : IDL.Text,
    'metaPixelId' : IDL.Text,
    'ga4Id' : IDL.Text,
  });
  const AdminRole = IDL.Variant({
    'manager' : IDL.Null,
    'owner' : IDL.Null,
    'support' : IDL.Null,
    'viewer' : IDL.Null,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'performer' : IDL.Principal,
    'target' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
  });
  const CeoProfile = IDL.Record({
    'title' : IDL.Text,
    'name' : IDL.Text,
    'instagramHandle' : IDL.Text,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const ComparisonRow = IDL.Record({
    'feature' : IDL.Text,
    'annual' : IDL.Bool,
    'monthly' : IDL.Bool,
  });
  const ErrorLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'errorType' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'principalId' : IDL.Opt(IDL.Text),
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'bookingId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'senderRole' : IDL.Text,
    'senderId' : UserId,
  });
  const MembershipPlan = IDL.Variant({
    'annual' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const UserMembership = IDL.Record({
    'status' : MembershipStatus,
    'endDate' : Timestamp,
    'userId' : UserId,
    'plan' : MembershipPlan,
    'startDate' : Timestamp,
  });
  const MembershipPlanConfig = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const PlanConfigs = IDL.Record({
    'annual' : MembershipPlanConfig,
    'monthly' : MembershipPlanConfig,
  });
  const ReviewId = IDL.Nat;
  const Review = IDL.Record({
    'id' : ReviewId,
    'bookingId' : IDL.Nat,
    'reviewerId' : UserId,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
    'vehicleId' : IDL.Nat,
  });
  const AdminEntry = IDL.Record({
    'principal' : IDL.Principal,
    'assignedAt' : Timestamp,
    'role' : AdminRole,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addFavorite' : IDL.Func([IDL.Text], [], []),
    'addTripPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : TripPhoto, 'err' : IDL.Text })],
        [],
      ),
    'adminAddVehicle' : IDL.Func(
        [VehicleInput],
        [IDL.Variant({ 'ok' : Vehicle, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Bool,
        ],
        [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminDeleteVehicle' : IDL.Func(
        [VehicleId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
    'adminGetEmailSubscribers' : IDL.Func([], [IDL.Vec(EmailSubscriber)], []),
    'adminGetPendingVerifications' : IDL.Func(
        [],
        [IDL.Vec(IDVerification)],
        [],
      ),
    'adminListAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], []),
    'adminListUsers' : IDL.Func([], [IDL.Vec(UserProfile)], []),
    'adminReportDamage' : IDL.Func(
        [BookingId, IDL.Text],
        [IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text })],
        [],
      ),
    'adminReviewVerification' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text],
        [IDL.Variant({ 'ok' : IDVerification, 'err' : IDL.Text })],
        [],
      ),
    'adminSendPromoEmail' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'adminSetAnalyticsSettings' : IDL.Func(
        [AnalyticsSettings],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetMembershipPricing' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetOpenAIKey' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetSiteStats' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetVehiclePhoto' : IDL.Func(
        [VehicleId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetVehicleSortOrders' : IDL.Func(
        [IDL.Vec(IDL.Tuple(VehicleId, IDL.Nat))],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateBlogPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateBookingStatus' : IDL.Func(
        [BookingId, BookingStatus],
        [IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdatePolicy' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateVehicle' : IDL.Func(
        [VehicleId, VehicleInput],
        [IDL.Variant({ 'ok' : Vehicle, 'err' : IDL.Text })],
        [],
      ),
    'askChat' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignRole' : IDL.Func(
        [IDL.Principal, AdminRole],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'cancelBooking' : IDL.Func([BookingId], [IDL.Bool], []),
    'cancelMembership' : IDL.Func([], [IDL.Bool], []),
    'checkVehicleAvailability' : IDL.Func(
        [VehicleId, IDL.Int, IDL.Int],
        [IDL.Bool],
        ['query'],
      ),
    'clearErrorLogs' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Int, PaymentMethod],
        [IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text })],
        [],
      ),
    'getAdminRole' : IDL.Func([IDL.Principal], [IDL.Opt(AdminRole)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeUserCount' : IDL.Nat,
            'bookingCountByVehicle' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'fleetUtilizationPercent' : IDL.Float64,
            'totalRevenue' : IDL.Float64,
          }),
        ],
        [],
      ),
    'getAnalyticsSettings' : IDL.Func([], [AnalyticsSettings], ['query']),
    'getAuditLog' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(AuditLog), 'err' : IDL.Text })],
        ['query'],
      ),
    'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBookingById' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getCeoProfile' : IDL.Func([], [CeoProfile], ['query']),
    'getComparisonRows' : IDL.Func([], [IDL.Vec(ComparisonRow)], ['query']),
    'getErrorLogs' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(ErrorLogEntry), 'err' : IDL.Text })],
        [],
      ),
    'getMembershipPricing' : IDL.Func(
        [],
        [IDL.Record({ 'annual' : IDL.Float64, 'monthly' : IDL.Float64 })],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(Message), 'err' : IDL.Text })],
        [],
      ),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getMyMembership' : IDL.Func([], [IDL.Opt(UserMembership)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyReferralCode' : IDL.Func([], [IDL.Text], []),
    'getPlanConfigs' : IDL.Func([], [PlanConfigs], ['query']),
    'getPolicies' : IDL.Func(
        [],
        [
          IDL.Record({
            'insuranceWaiverTerms' : IDL.Text,
            'cancellationPolicy' : IDL.Text,
            'damagePolicy' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getReferralStats' : IDL.Func(
        [],
        [IDL.Record({ 'code' : IDL.Text, 'referralCount' : IDL.Nat })],
        [],
      ),
    'getSiteStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'conciergeSupport' : IDL.Text,
            'eliteVehicles' : IDL.Nat,
            'fiveStarReviews' : IDL.Text,
            'satisfiedClients' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getTripPhotos' : IDL.Func([IDL.Text], [IDL.Vec(TripPhoto)], []),
    'getVehicle' : IDL.Func([VehicleId], [IDL.Opt(Vehicle)], ['query']),
    'getVehicleReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getVehicleSortOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(VehicleId, IDL.Nat))],
        ['query'],
      ),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listAdminsWithRoles' : IDL.Func([], [IDL.Vec(AdminEntry)], ['query']),
    'listPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'registerProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'removeAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeFavorite' : IDL.Func([IDL.Text], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
        [],
      ),
    'setCeoProfile' : IDL.Func([CeoProfile], [], []),
    'setComparisonRows' : IDL.Func(
        [IDL.Vec(ComparisonRow)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setPlanConfigs' : IDL.Func(
        [PlanConfigs],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitIDVerification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDVerification, 'err' : IDL.Text })],
        [],
      ),
    'submitReview' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Review, 'err' : IDL.Text })],
        [],
      ),
    'subscribeMembership' : IDL.Func(
        [MembershipPlan],
        [IDL.Variant({ 'ok' : UserMembership, 'err' : IDL.Text })],
        [],
      ),
    'subscribeToEmailList' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transferOwnership' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateMembershipStatus' : IDL.Func(
        [UserId, MembershipStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(UserProfile)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };